-- Bang cau hinh key + value_1 .. value_5 (doc/ghi/xoa qua service_role + authenticated).

create table if not exists public.app_config_kv (
  id bigint generated by default as identity primary key,
  config_key text not null,
  value_1 text null,
  value_2 text null,
  value_3 text null,
  value_4 text null,
  value_5 text null,
  description text null,
  category text null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint uq_app_config_kv_config_key unique (config_key),
  constraint ck_app_config_kv_key_not_blank check (length(trim(config_key)) > 0)
);

create index if not exists idx_app_config_kv_category on public.app_config_kv (category);
create index if not exists idx_app_config_kv_active on public.app_config_kv (is_active)
  where is_active = true;

comment on table public.app_config_kv is
  'Cau hinh key-value (value_1..value_5); ung dung parse theo config_key.';
comment on column public.app_config_kv.config_key is 'Dinh danh duy nhat, vi du split.agency_pct';

create or replace function public.set_app_config_kv_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_app_config_kv_updated on public.app_config_kv;
create trigger trg_app_config_kv_updated
  before update on public.app_config_kv
  for each row
  execute procedure public.set_app_config_kv_updated_at();

alter table public.app_config_kv disable row level security;

grant select, insert, update, delete on table public.app_config_kv to service_role;
grant select, insert, update, delete on table public.app_config_kv to authenticated;

grant usage, select on sequence public.app_config_kv_id_seq to service_role;
grant usage, select on sequence public.app_config_kv_id_seq to authenticated;
