-- Cau hinh bot (nhom bot): loai REP/GHI, uu tien 1-100.

create table if not exists public.bot_group (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id_bot text null,
  name_bot text null,
  type_bot text not null default 'REP',
  priority smallint not null default 1,
  constraint bot_group_pkey primary key (id),
  constraint ck_bot_group_type_bot check (type_bot in ('REP', 'GHI')),
  constraint ck_bot_group_priority check (priority >= 1 and priority <= 100)
);

create index if not exists idx_bot_group_priority on public.bot_group (priority asc, id asc);

comment on table public.bot_group is 'Cau hinh bot theo nhom: id_bot, name_bot, type REP/GHI, priority 1-100.';
comment on column public.bot_group.type_bot is 'REP hoac GHI.';
comment on column public.bot_group.priority is 'Uu tien 1 (cao) den 100 (thap), hoac nguoc lai tuy nghiep vu — gioi han 1-100.';

alter table public.bot_group disable row level security;
