-- Gán affiliate id cho bot (aff_bot).

create table if not exists public.aff_bot (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id_aff text null,
  constraint aff_bot_pkey primary key (id)
);

create index if not exists idx_aff_bot_id_aff on public.aff_bot (id_aff);

comment on table public.aff_bot is 'Danh sach affiliate id gan voi bot.';
comment on column public.aff_bot.id_aff is 'Ma affiliate (nullable).';

alter table public.aff_bot disable row level security;
