-- Map bot -> nhom (local / global) cho UI Cau hinh bot.

create table if not exists public.bot_datagroup (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id_bot text null,
  id_localgroup text null,
  id_globalgroup text null,
  constraint bot_datagroup_pkey primary key (id)
);

create index if not exists idx_bot_datagroup_id_bot
  on public.bot_datagroup (id_bot);

create index if not exists idx_bot_datagroup_id_globalgroup
  on public.bot_datagroup (id_globalgroup);

comment on table public.bot_datagroup is 'Map id_bot -> id_localgroup / id_globalgroup (noi zalo_groups.id_global).';

alter table public.bot_datagroup disable row level security;
